import type {VisualDefinition} from './types';
import {
  TitleHero,
  TitleHeroProps,
  SectionIntro,
  SectionIntroProps,
  Quote,
  QuoteProps,
  KeyTakeaway,
  KeyTakeawayProps,
  Summary,
  SummaryProps,
  Outro,
  OutroProps,
} from './components/typography';
import {
  DefinitionCard,
  DefinitionCardProps,
  BulletReveal,
  BulletRevealProps,
  Comparison,
  ComparisonProps,
  ProsCons,
  ProsConsProps,
  Timeline,
  TimelineProps,
  CashflowTimeline,
  CashflowTimelineProps,
  ProcessFlow,
  ProcessFlowProps,
  FlowChart,
  FlowChartProps,
  BeforeAfter,
  BeforeAfterProps,
} from './components/explanation';
import {
  BarChart,
  BarChartProps,
  LineChart,
  LineChartProps,
  AreaChart,
  AreaChartProps,
  DonutChart,
  DonutChartProps,
  DataTable,
  DataTableProps,
  NumberCounter,
  NumberCounterProps,
  Formula,
  FormulaProps,
  FormulaDerivation,
  FormulaDerivationProps,
  EquationHighlight,
  EquationHighlightProps,
  StepByStepCalculation,
  StepByStepCalculationProps,
} from './components/quantitative';
import {
  CodeBlock,
  CodeBlockProps,
  TerminalDemo,
  TerminalDemoProps,
  BrowserFrame,
  BrowserFrameProps,
  ScreenshotCallout,
  ScreenshotCalloutProps,
} from './components/technical';
import {
  RelationshipDiagram,
  RelationshipDiagramProps,
  NetworkDiagram,
  NetworkDiagramProps,
  Matrix,
  MatrixProps,
  Pyramid,
  PyramidProps,
  Funnel,
  FunnelProps,
} from './components/relationships';
import {QuizQuestion, QuizQuestionProps, QuizAnswer, QuizAnswerProps} from './components/assessment';

export const visualRegistry: Readonly<Record<string, VisualDefinition<unknown>>> = {
  'title-hero': {
    id: 'title-hero',
    group: 'typography',
    intent: 'Introduce the topic with a bold title',
    suitability: ['opening', 'topic introduction', 'high-level framing'],
    avoidance: ['detailed data', 'step-by-step instruction'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:title-hero',
    propsSchema: TitleHeroProps,
    component: TitleHero,
  },
  'section-intro': {
    id: 'section-intro',
    group: 'typography',
    intent: 'Introduce a section with heading and agenda',
    suitability: ['section transitions', 'chapter openings'],
    avoidance: ['final scenes', 'dense quantitative content'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:section-intro',
    propsSchema: SectionIntroProps,
    component: SectionIntro,
  },
  'quote': {
    id: 'quote',
    group: 'typography',
    intent: 'Present a memorable quote',
    suitability: ['expert quotes', 'emphasis moments'],
    avoidance: ['instructions', 'technical detail'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:quote',
    propsSchema: QuoteProps,
    component: Quote,
  },
  'key-takeaway': {
    id: 'key-takeaway',
    group: 'typography',
    intent: 'Highlight the single most important point',
    suitability: ['recap', 'emphasis', 'transition points'],
    avoidance: ['data tables', 'long lists'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:key-takeaway',
    propsSchema: KeyTakeawayProps,
    component: KeyTakeaway,
  },
  'summary': {
    id: 'summary',
    group: 'typography',
    intent: 'Recap the covered points at the end',
    suitability: ['conclusions', 'recap sections'],
    avoidance: ['new material'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:summary',
    propsSchema: SummaryProps,
    component: Summary,
  },
  'outro': {
    id: 'outro',
    group: 'typography',
    intent: 'Close the video with a call to continue',
    suitability: ['final scene'],
    avoidance: ['educational content'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:outro',
    propsSchema: OutroProps,
    component: Outro,
  },
  'definition-card': {
    id: 'definition-card',
    group: 'explanation',
    intent: 'Define a term with an example',
    suitability: ['concept definition', 'terminology'],
    avoidance: ['comparisons', 'time series'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:definition-card',
    propsSchema: DefinitionCardProps,
    component: DefinitionCard,
  },
  'bullet-reveal': {
    id: 'bullet-reveal',
    group: 'explanation',
    intent: 'Reveal a list of points one by one',
    suitability: ['lists', 'arguments', 'steps overview'],
    avoidance: ['comparisons of two items'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:bullet-reveal',
    propsSchema: BulletRevealProps,
    component: BulletReveal,
  },
  'comparison': {
    id: 'comparison',
    group: 'explanation',
    intent: 'Compare a small number of items side by side',
    suitability: ['two to four alternatives', 'feature contrast'],
    avoidance: ['more than four items', 'sequential process'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:comparison',
    propsSchema: ComparisonProps,
    component: Comparison,
  },
  'pros-cons': {
    id: 'pros-cons',
    group: 'explanation',
    intent: 'Weigh advantages against disadvantages',
    suitability: ['trade-off analysis', 'decision framing'],
    avoidance: ['single-fact statements'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:pros-cons',
    propsSchema: ProsConsProps,
    component: ProsCons,
  },
  'timeline': {
    id: 'timeline',
    group: 'explanation',
    intent: 'Show chronological sequence of events',
    suitability: ['history', 'project phases', 'process milestones'],
    avoidance: ['numerical comparisons'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:timeline',
    propsSchema: TimelineProps,
    component: Timeline,
  },
  'cashflow-timeline': {
    id: 'cashflow-timeline',
    group: 'explanation',
    intent: 'Visualize cash inflows and outflows over time',
    suitability: ['finance', 'discounting', 'investment analysis'],
    avoidance: ['non-monetary data'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:cashflow-timeline',
    propsSchema: CashflowTimelineProps,
    component: CashflowTimeline,
  },
  'process-flow': {
    id: 'process-flow',
    group: 'explanation',
    intent: 'Show a linear process from start to finish',
    suitability: ['workflows', 'pipelines', 'sequential steps'],
    avoidance: ['branching logic'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:process-flow',
    propsSchema: ProcessFlowProps,
    component: ProcessFlow,
  },
  'flow-chart': {
    id: 'flow-chart',
    group: 'explanation',
    intent: 'Show branching decisions in a flow',
    suitability: ['decision trees', 'algorithms with branches'],
    avoidance: ['long timelines'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:flow-chart',
    propsSchema: FlowChartProps,
    component: FlowChart,
  },
  'before-after': {
    id: 'before-after',
    group: 'explanation',
    intent: 'Contrast a before state with an after state',
    suitability: ['transformation', 'improvement stories'],
    avoidance: ['quantitative detail'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:before-after',
    propsSchema: BeforeAfterProps,
    component: BeforeAfter,
  },
  'bar-chart': {
    id: 'bar-chart',
    group: 'quantitative',
    intent: 'Compare discrete values across categories',
    suitability: ['categorical comparisons', 'rankings'],
    avoidance: ['time series trends'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:bar-chart',
    propsSchema: BarChartProps,
    component: BarChart,
  },
  'line-chart': {
    id: 'line-chart',
    group: 'quantitative',
    intent: 'Show a trend over time',
    suitability: ['time series', 'trends'],
    avoidance: ['categorical comparisons'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:line-chart',
    propsSchema: LineChartProps,
    component: LineChart,
  },
  'area-chart': {
    id: 'area-chart',
    group: 'quantitative',
    intent: 'Show magnitude over time with filled area',
    suitability: ['accumulated values', 'volume trends'],
    avoidance: ['fine-grained comparisons'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:area-chart',
    propsSchema: AreaChartProps,
    component: AreaChart,
  },
  'donut-chart': {
    id: 'donut-chart',
    group: 'quantitative',
    intent: 'Show proportional composition of a whole',
    suitability: ['shares', 'percentages', 'portfolio mix'],
    avoidance: ['more than six slices'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:donut-chart',
    propsSchema: DonutChartProps,
    component: DonutChart,
  },
  'data-table': {
    id: 'data-table',
    group: 'quantitative',
    intent: 'Present structured tabular data',
    suitability: ['precise values', 'multi-column records'],
    avoidance: ['narrative explanation'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:data-table',
    propsSchema: DataTableProps,
    component: DataTable,
  },
  'number-counter': {
    id: 'number-counter',
    group: 'quantitative',
    intent: 'Emphasize a single number counting up',
    suitability: ['statistics', 'headline figures'],
    avoidance: ['multi-value data'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:number-counter',
    propsSchema: NumberCounterProps,
    component: NumberCounter,
  },
  'formula': {
    id: 'formula',
    group: 'quantitative',
    intent: 'Present a formula with context',
    suitability: ['mathematical definitions', 'equations'],
    avoidance: ['long derivations'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:formula',
    propsSchema: FormulaProps,
    component: Formula,
  },
  'formula-derivation': {
    id: 'formula-derivation',
    group: 'quantitative',
    intent: 'Derive a formula step by step',
    suitability: ['proofs', 'derivations'],
    avoidance: ['simple formulas'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:formula-derivation',
    propsSchema: FormulaDerivationProps,
    component: FormulaDerivation,
  },
  'equation-highlight': {
    id: 'equation-highlight',
    group: 'quantitative',
    intent: 'Highlight parts of an equation',
    suitability: ['explaining variables', 'annotating formulas'],
    avoidance: ['whole derivations'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:equation-highlight',
    propsSchema: EquationHighlightProps,
    component: EquationHighlight,
  },
  'step-by-step-calculation': {
    id: 'step-by-step-calculation',
    group: 'quantitative',
    intent: 'Walk through a worked calculation',
    suitability: ['worked examples', 'finance computations'],
    avoidance: ['abstract theory'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:step-by-step-calculation',
    propsSchema: StepByStepCalculationProps,
    component: StepByStepCalculation,
  },
  'code-block': {
    id: 'code-block',
    group: 'technical',
    intent: 'Show source code with line numbers',
    suitability: ['programming', 'API examples'],
    avoidance: ['business narrative'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:code-block',
    propsSchema: CodeBlockProps,
    component: CodeBlock,
  },
  'terminal-demo': {
    id: 'terminal-demo',
    group: 'technical',
    intent: 'Show a terminal session',
    suitability: ['CLI tools', 'command examples'],
    avoidance: ['non-technical topics'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:terminal-demo',
    propsSchema: TerminalDemoProps,
    component: TerminalDemo,
  },
  'browser-frame': {
    id: 'browser-frame',
    group: 'technical',
    intent: 'Present a browser window mockup',
    suitability: ['web products', 'screens'],
    avoidance: ['abstract concepts'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:browser-frame',
    propsSchema: BrowserFrameProps,
    component: BrowserFrame,
  },
  'screenshot-callout': {
    id: 'screenshot-callout',
    group: 'technical',
    intent: 'Explain parts of a screenshot',
    suitability: ['UI walkthroughs', 'tool explanations'],
    avoidance: ['pure data'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:screenshot-callout',
    propsSchema: ScreenshotCalloutProps,
    component: ScreenshotCallout,
  },
  'relationship-diagram': {
    id: 'relationship-diagram',
    group: 'relationships',
    intent: 'Show how one concept relates to others',
    suitability: ['concept maps', 'cause and effect'],
    avoidance: ['linear processes'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:relationship-diagram',
    propsSchema: RelationshipDiagramProps,
    component: RelationshipDiagram,
  },
  'network-diagram': {
    id: 'network-diagram',
    group: 'relationships',
    intent: 'Show a hub-and-spoke network',
    suitability: ['systems', 'ecosystems'],
    avoidance: ['simple pairwise comparisons'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:network-diagram',
    propsSchema: NetworkDiagramProps,
    component: NetworkDiagram,
  },
  'matrix': {
    id: 'matrix',
    group: 'relationships',
    intent: 'Place items in a 2x2 matrix',
    suitability: ['positioning', 'frameworks'],
    avoidance: ['single sequence'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:matrix',
    propsSchema: MatrixProps,
    component: Matrix,
  },
  'pyramid': {
    id: 'pyramid',
    group: 'relationships',
    intent: 'Show hierarchical structure as a pyramid',
    suitability: ['hierarchies', 'priorities'],
    avoidance: ['temporal sequences'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:pyramid',
    propsSchema: PyramidProps,
    component: Pyramid,
  },
  'funnel': {
    id: 'funnel',
    group: 'relationships',
    intent: 'Show conversion or narrowing stages',
    suitability: ['conversion funnels', 'filters'],
    avoidance: ['growing processes'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:funnel',
    propsSchema: FunnelProps,
    component: Funnel,
  },
  'quiz-question': {
    id: 'quiz-question',
    group: 'assessment',
    intent: 'Pose a multiple-choice question',
    suitability: ['checks for understanding'],
    avoidance: ['answers in the same scene'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:quiz-question',
    propsSchema: QuizQuestionProps,
    component: QuizQuestion,
  },
  'quiz-answer': {
    id: 'quiz-answer',
    group: 'assessment',
    intent: 'Reveal the correct answer with explanation',
    suitability: ['answers after questions'],
    avoidance: ['new questions'],
    schemaVersion: 1,
    engine: 'remotion',
    preview: 'fixture:quiz-answer',
    propsSchema: QuizAnswerProps,
    component: QuizAnswer,
  },
} as const;

export function getVisualDefinition(id: string): VisualDefinition<unknown> | undefined {
  return (visualRegistry as Readonly<Record<string, VisualDefinition<unknown>>>)[id];
}
