import type {ThemeTokens} from '@motionknowledge/schemas';

/**
 * The six production style packs. Each entry is a full visual grammar
 * (tokens + identity metadata) — not a colour preset. Components stay
 * semantic; `visualLanguage` selects the treatment family.
 */

export interface VisualStyleMetadata {
  id: string;
  name: string;
  description: string;
  tags: string[];
  version: number;
  aspectRatios: ReadonlyArray<'16:9' | '9:16'>;
  suitability: string[];
  motionPersonality: string;
  componentVariants: Readonly<Record<string, string>>;
  preview: string;
}

export interface VisualStylePack extends VisualStyleMetadata {
  tokens: ThemeTokens;
}

export const signatureStyle: VisualStylePack = {
  id: 'signature',
  name: 'MotionKnowledge Signature',
  description: 'Sophisticated dark motion graphics with teal accents, clean animated diagrams and polished depth. The MotionKnowledge identity.',
  tags: ['dark', 'technology', 'saas', 'modern', 'default'],
  version: 1,
  aspectRatios: ['16:9', '9:16'],
  suitability: ['explainer', 'technology', 'science', 'general education'],
  motionPersonality: 'smooth springs, slide-up reveals, subtle depth',
  componentVariants: {'process-flow': 'polished'},
  preview: 'showcase:signature',
  tokens: {
    colors: {
      background: '#08111F',
      surface: '#10213A',
      surfaceAlt: '#0D1B30',
      primary: '#59D5E0',
      primaryAlt: '#8EE9F0',
      accent: '#F7C948',
      text: '#F8FAFC',
      muted: '#9FB2C8',
      danger: '#FB7185',
      success: '#4ADE80',
      onAccent: '#06202B',
      onSurface: '#F8FAFC',
      chartPalette: ['#59D5E0', '#F7C948', '#8B5CF6', '#4ADE80', '#FB923C', '#38BDF8'],
    },
    fonts: {
      heading: `'Inter', 'Helvetica Neue', system-ui, sans-serif`,
      body: `'Inter', 'Helvetica Neue', system-ui, sans-serif`,
      mono: `'JetBrains Mono', 'SF Mono', Menlo, monospace`,
    },
    typography: {display: 92, heading: 64, subheading: 40, body: 32, caption: 24},
    background: {
      treatment: 'gradient',
      gradient: 'linear-gradient(180deg, #0A1526 0%, #08111F 100%)',
      texture: 'none',
    },
    surfaces: {
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      borderStyle: 'solid',
      shadow: '0 24px 60px rgba(0,0,0,0.45)',
    },
    strokes: {width: 3, style: 'solid', color: 'rgba(255,255,255,0.2)'},
    borders: {width: 1, color: 'rgba(255,255,255,0.12)', style: 'solid'},
    shadows: {
      sm: '0 4px 12px rgba(0,0,0,0.3)',
      md: '0 12px 32px rgba(0,0,0,0.4)',
      lg: '0 24px 60px rgba(0,0,0,0.45)',
    },
    radius: {sm: 10, md: 18, lg: 28},
    spacing: {xs: 8, sm: 16, md: 24, lg: 40, xl: 64},
    safeAreaX: 96,
    safeAreaY: 64,
    motion: {
      fast: 12,
      normal: 24,
      slow: 40,
      reveal: 'slide-up',
      spring: {damping: 200, stiffness: 200},
      easing: 'linear',
    },
    transitions: {family: 'crossfade', durationFrames: 18},
    density: 'comfortable',
    visualLanguage: 'polished',
    variants: {'process-flow': 'polished'},
    sceneLayout: {align: 'center', titlePosition: 'center'},
    caption: {background: 'rgba(8,17,31,0.7)', text: '#F8FAFC', size: 34, weight: 600, treatment: 'pill'},
    thumbnail: {background: '#08111F', text: '#F8FAFC', accent: '#59D5E0'},
    illustration: 'flat-graphic',
    icon: 'line',
    chart: 'modern',
    diagram: 'polished',
    annotation: 'callout',
    emphasis: 'color',
  },
};

export const handwrittenStyle: VisualStylePack = {
  id: 'handwritten',
  name: 'Handwritten / Whiteboard',
  description: 'Warm paper background, sketch-like boxes and arrows, marker highlights and animated stroke drawing. The explanation is constructed while you watch.',
  tags: ['whiteboard', 'hand-drawn', 'sketch', 'education', 'teaching'],
  version: 1,
  aspectRatios: ['16:9', '9:16'],
  suitability: ['tutorial', 'teaching', 'difficult concepts', 'course lesson'],
  motionPersonality: 'stroke-drawing reveals, gentle springy motion, constructed feel',
  componentVariants: {'process-flow': 'hand-drawn'},
  preview: 'showcase:handwritten',
  tokens: {
    colors: {
      background: '#FBF5E8',
      surface: '#FFFDF6',
      surfaceAlt: '#F3EAD5',
      primary: '#2B7BD6',
      primaryAlt: '#5C9FE8',
      accent: '#E8A33D',
      text: '#2E2A24',
      muted: '#7A7266',
      danger: '#D64550',
      success: '#4E9A51',
      onAccent: '#FFFFFF',
      onSurface: '#2E2A24',
      chartPalette: ['#2B7BD6', '#E8A33D', '#C0564F', '#4E9A51', '#8B6FB8', '#D98E32'],
    },
    fonts: {
      heading: `'Bradley Hand', 'Chalkboard SE', 'Comic Sans MS', cursive`,
      body: `'Bradley Hand', 'Chalkboard SE', 'Comic Sans MS', cursive`,
      mono: `'Bradley Hand', 'Chalkboard SE', 'Comic Sans MS', cursive`,
    },
    typography: {display: 88, heading: 60, subheading: 38, body: 34, caption: 26},
    background: {treatment: 'paper', gradient: 'none', texture: 'paper-grain'},
    surfaces: {
      borderWidth: 2,
      borderColor: 'rgba(46,42,36,0.4)',
      borderStyle: 'solid',
      shadow: 'none',
    },
    strokes: {width: 3, style: 'sketch', color: 'rgba(46,42,36,0.55)'},
    borders: {width: 2, color: 'rgba(46,42,36,0.3)', style: 'dashed'},
    shadows: {sm: 'none', md: 'none', lg: 'none'},
    radius: {sm: 4, md: 10, lg: 16},
    spacing: {xs: 8, sm: 16, md: 24, lg: 40, xl: 64},
    safeAreaX: 96,
    safeAreaY: 64,
    motion: {
      fast: 14,
      normal: 28,
      slow: 48,
      reveal: 'draw',
      spring: {damping: 14, stiffness: 120},
      easing: 'ease-out',
    },
    transitions: {family: 'draw', durationFrames: 24},
    density: 'comfortable',
    visualLanguage: 'hand-drawn',
    variants: {'process-flow': 'hand-drawn'},
    sceneLayout: {align: 'start', titlePosition: 'top'},
    caption: {background: 'rgba(251,245,232,0.92)', text: '#2E2A24', size: 32, weight: 600, treatment: 'marker'},
    thumbnail: {background: '#FBF5E8', text: '#2E2A24', accent: '#E8A33D'},
    illustration: 'sketch',
    icon: 'hand-drawn',
    chart: 'sketch',
    diagram: 'hand-drawn',
    annotation: 'marker',
    emphasis: 'underline',
  },
};

export const presentationStyle: VisualStylePack = {
  id: 'presentation',
  name: 'Clean Presentation',
  description: 'Structured slide compositions with strong title hierarchy, cards, panels and clean charts. Premium corporate, never a static deck.',
  tags: ['slides', 'presentation', 'corporate', 'training', 'ppt'],
  version: 1,
  aspectRatios: ['16:9', '9:16'],
  suitability: ['business', 'training', 'course lesson', 'corporate'],
  motionPersonality: 'restrained slide reveals, crisp springs, controlled pacing',
  componentVariants: {'process-flow': 'structured'},
  preview: 'showcase:presentation',
  tokens: {
    colors: {
      background: '#F4F6FA',
      surface: '#FFFFFF',
      surfaceAlt: '#EEF1F7',
      primary: '#2557D6',
      primaryAlt: '#6B8BE8',
      accent: '#F2A93B',
      text: '#1A2233',
      muted: '#64748B',
      danger: '#D64545',
      success: '#2E9E5B',
      onAccent: '#FFFFFF',
      onSurface: '#1A2233',
      chartPalette: ['#2557D6', '#F2A93B', '#2E9E5B', '#9B59B6', '#E67E22', '#16A085'],
    },
    fonts: {
      heading: `'Segoe UI', 'Inter', system-ui, sans-serif`,
      body: `'Segoe UI', 'Inter', system-ui, sans-serif`,
      mono: `'Cascadia Mono', 'JetBrains Mono', Menlo, monospace`,
    },
    typography: {display: 84, heading: 58, subheading: 38, body: 30, caption: 22},
    background: {treatment: 'flat', gradient: 'none', texture: 'none'},
    surfaces: {
      borderWidth: 1,
      borderColor: 'rgba(26,34,51,0.08)',
      borderStyle: 'solid',
      shadow: '0 8px 24px rgba(26,34,51,0.08)',
    },
    strokes: {width: 2, style: 'solid', color: 'rgba(26,34,51,0.15)'},
    borders: {width: 1, color: 'rgba(26,34,51,0.12)', style: 'solid'},
    shadows: {
      sm: '0 2px 8px rgba(26,34,51,0.06)',
      md: '0 8px 24px rgba(26,34,51,0.08)',
      lg: '0 16px 40px rgba(26,34,51,0.12)',
    },
    radius: {sm: 8, md: 12, lg: 16},
    spacing: {xs: 8, sm: 16, md: 24, lg: 40, xl: 64},
    safeAreaX: 96,
    safeAreaY: 64,
    motion: {
      fast: 10,
      normal: 20,
      slow: 32,
      reveal: 'slide-up',
      spring: {damping: 30, stiffness: 260},
      easing: 'ease-out',
    },
    transitions: {family: 'slide', durationFrames: 16},
    density: 'comfortable',
    visualLanguage: 'structured',
    variants: {'process-flow': 'structured'},
    sceneLayout: {align: 'start', titlePosition: 'top'},
    caption: {background: 'rgba(26,34,51,0.75)', text: '#FFFFFF', size: 30, weight: 600, treatment: 'pill'},
    thumbnail: {background: '#2557D6', text: '#FFFFFF', accent: '#F2A93B'},
    illustration: 'flat-graphic',
    icon: 'line',
    chart: 'clean',
    diagram: 'structured',
    annotation: 'callout',
    emphasis: 'color',
  },
};

export const editorialStyle: VisualStylePack = {
  id: 'editorial',
  name: 'Editorial Infographic',
  description: 'Bold typography, large numerical callouts, strong colour blocks and infographic charts. Built for fact-heavy explainers and social content.',
  tags: ['infographic', 'bold', 'social', 'youtube', 'statistics'],
  version: 1,
  aspectRatios: ['16:9', '9:16'],
  suitability: ['explainer', 'statistics', 'facts', 'social media', 'news'],
  motionPersonality: 'bold scale reveals, punchy timing, dynamic but controlled',
  componentVariants: {'process-flow': 'infographic'},
  preview: 'showcase:editorial',
  tokens: {
    colors: {
      background: '#F7F7F4',
      surface: '#FFFFFF',
      surfaceAlt: '#EDEDE8',
      primary: '#1B1B1F',
      primaryAlt: '#3A3A40',
      accent: '#FF4D2E',
      text: '#1B1B1F',
      muted: '#6B6B70',
      danger: '#C8102E',
      success: '#0F9D58',
      onAccent: '#FFFFFF',
      onSurface: '#1B1B1F',
      chartPalette: ['#FF4D2E', '#1B1B1F', '#FFC531', '#0F9D58', '#2D6CDF', '#C8102E'],
    },
    fonts: {
      heading: `'Archivo Black', 'Arial Black', system-ui, sans-serif`,
      body: `'Inter', 'Helvetica Neue', system-ui, sans-serif`,
      mono: `'JetBrains Mono', 'SF Mono', Menlo, monospace`,
    },
    typography: {display: 110, heading: 72, subheading: 44, body: 32, caption: 22},
    background: {treatment: 'flat', gradient: 'none', texture: 'none'},
    surfaces: {
      borderWidth: 4,
      borderColor: 'rgba(27,27,31,0.9)',
      borderStyle: 'solid',
      shadow: 'none',
    },
    strokes: {width: 4, style: 'solid', color: 'rgba(27,27,31,0.9)'},
    borders: {width: 3, color: 'rgba(27,27,31,0.9)', style: 'solid'},
    shadows: {sm: 'none', md: 'none', lg: 'none'},
    radius: {sm: 0, md: 0, lg: 0},
    spacing: {xs: 8, sm: 16, md: 24, lg: 40, xl: 64},
    safeAreaX: 80,
    safeAreaY: 56,
    motion: {
      fast: 10,
      normal: 20,
      slow: 34,
      reveal: 'scale',
      spring: {damping: 24, stiffness: 300},
      easing: 'ease-in-out',
    },
    transitions: {family: 'scale', durationFrames: 16},
    density: 'compact',
    visualLanguage: 'infographic',
    variants: {'process-flow': 'infographic'},
    sceneLayout: {align: 'start', titlePosition: 'top'},
    caption: {background: 'rgba(27,27,31,0.9)', text: '#FFFFFF', size: 34, weight: 800, treatment: 'block'},
    thumbnail: {background: '#FF4D2E', text: '#FFFFFF', accent: '#1B1B1F'},
    illustration: 'flat-graphic',
    icon: 'filled',
    chart: 'infographic',
    diagram: 'block',
    annotation: 'label',
    emphasis: 'block',
  },
};

export const businessStyle: VisualStylePack = {
  id: 'business',
  name: 'Business Briefing',
  description: 'KPI cards, charts, tables, timelines and professional annotation. High information density without clutter for finance and strategy.',
  tags: ['business', 'finance', 'strategy', 'kpi', 'corporate training'],
  version: 1,
  aspectRatios: ['16:9', '9:16'],
  suitability: ['finance', 'economics', 'strategy', 'corporate training', 'analysis'],
  motionPersonality: 'restrained motion, crisp fades, professional pacing',
  componentVariants: {'process-flow': 'business'},
  preview: 'showcase:business',
  tokens: {
    colors: {
      background: '#0F172A',
      surface: '#1E293B',
      surfaceAlt: '#172033',
      primary: '#3B82F6',
      primaryAlt: '#60A5FA',
      accent: '#F59E0B',
      text: '#F1F5F9',
      muted: '#94A3B8',
      danger: '#EF4444',
      success: '#22C55E',
      onAccent: '#0B1220',
      onSurface: '#F1F5F9',
      chartPalette: ['#3B82F6', '#F59E0B', '#22C55E', '#8B5CF6', '#EC4899', '#14B8A6'],
    },
    fonts: {
      heading: `'Inter', 'Helvetica Neue', system-ui, sans-serif`,
      body: `'Inter', 'Helvetica Neue', system-ui, sans-serif`,
      mono: `'JetBrains Mono', 'SF Mono', Menlo, monospace`,
    },
    typography: {display: 80, heading: 56, subheading: 36, body: 30, caption: 22},
    background: {treatment: 'flat', gradient: 'none', texture: 'none'},
    surfaces: {
      borderWidth: 1,
      borderColor: 'rgba(241,245,249,0.1)',
      borderStyle: 'solid',
      shadow: '0 8px 20px rgba(0,0,0,0.25)',
    },
    strokes: {width: 2, style: 'solid', color: 'rgba(241,245,249,0.18)'},
    borders: {width: 1, color: 'rgba(241,245,249,0.12)', style: 'solid'},
    shadows: {
      sm: '0 2px 6px rgba(0,0,0,0.2)',
      md: '0 8px 20px rgba(0,0,0,0.25)',
      lg: '0 16px 36px rgba(0,0,0,0.3)',
    },
    radius: {sm: 6, md: 10, lg: 14},
    spacing: {xs: 8, sm: 14, md: 22, lg: 34, xl: 56},
    safeAreaX: 88,
    safeAreaY: 56,
    motion: {
      fast: 8,
      normal: 16,
      slow: 26,
      reveal: 'fade',
      spring: {damping: 40, stiffness: 320},
      easing: 'linear',
    },
    transitions: {family: 'crossfade', durationFrames: 12},
    density: 'compact',
    visualLanguage: 'business',
    variants: {'process-flow': 'business'},
    sceneLayout: {align: 'start', titlePosition: 'top'},
    caption: {background: 'rgba(15,23,42,0.85)', text: '#F1F5F9', size: 30, weight: 600, treatment: 'pill'},
    thumbnail: {background: '#0F172A', text: '#F1F5F9', accent: '#3B82F6'},
    illustration: 'flat-graphic',
    icon: 'line',
    chart: 'kpi',
    diagram: 'structured',
    annotation: 'callout',
    emphasis: 'color',
  },
};

export const minimalStyle: VisualStylePack = {
  id: 'minimal',
  name: 'Minimal Knowledge',
  description: 'Substantial whitespace, large typography, simple geometry and a limited palette. Maximum clarity with gentle motion.',
  tags: ['minimal', 'clean', 'whitespace', 'simple', 'accessible'],
  version: 1,
  aspectRatios: ['16:9', '9:16'],
  suitability: ['concepts', 'definitions', 'philosophy', 'accessible education'],
  motionPersonality: 'gentle fades, unhurried timing, maximum calm',
  componentVariants: {'process-flow': 'minimal'},
  preview: 'showcase:minimal',
  tokens: {
    colors: {
      background: '#FAFAFA',
      surface: '#FFFFFF',
      surfaceAlt: '#F2F2F2',
      primary: '#1B1B1B',
      primaryAlt: '#4A4A4A',
      accent: '#2E6FDB',
      text: '#1B1B1B',
      muted: '#8A8A8E',
      danger: '#C0392B',
      success: '#2E7D32',
      onAccent: '#FFFFFF',
      onSurface: '#1B1B1B',
      chartPalette: ['#1B1B1B', '#2E6FDB', '#8A8A8E', '#C7C7CC', '#5B5B60', '#2E6FDB'],
    },
    fonts: {
      heading: `'Inter', 'Helvetica Neue', system-ui, sans-serif`,
      body: `'Inter', 'Helvetica Neue', system-ui, sans-serif`,
      mono: `'SF Mono', Menlo, monospace`,
    },
    typography: {display: 100, heading: 68, subheading: 42, body: 32, caption: 24},
    background: {treatment: 'flat', gradient: 'none', texture: 'none'},
    surfaces: {
      borderWidth: 1,
      borderColor: 'rgba(27,27,27,0.08)',
      borderStyle: 'solid',
      shadow: 'none',
    },
    strokes: {width: 2, style: 'solid', color: 'rgba(27,27,27,0.15)'},
    borders: {width: 1, color: 'rgba(27,27,27,0.12)', style: 'solid'},
    shadows: {sm: 'none', md: 'none', lg: 'none'},
    radius: {sm: 4, md: 8, lg: 12},
    spacing: {xs: 12, sm: 24, md: 40, lg: 64, xl: 96},
    safeAreaX: 120,
    safeAreaY: 80,
    motion: {
      fast: 16,
      normal: 32,
      slow: 56,
      reveal: 'fade',
      spring: {damping: 60, stiffness: 160},
      easing: 'ease-out',
    },
    transitions: {family: 'crossfade', durationFrames: 24},
    density: 'spacious',
    visualLanguage: 'minimal',
    variants: {'process-flow': 'minimal'},
    sceneLayout: {align: 'start', titlePosition: 'top'},
    caption: {background: 'rgba(250,250,250,0.9)', text: '#1B1B1B', size: 32, weight: 500, treatment: 'flat'},
    thumbnail: {background: '#FAFAFA', text: '#1B1B1B', accent: '#2E6FDB'},
    illustration: 'flat-graphic',
    icon: 'line',
    chart: 'minimal',
    diagram: 'line',
    annotation: 'label',
    emphasis: 'underline',
  },
};
