import {NextResponse} from 'next/server';
import {getSessionUser} from '../../../../../../lib/supabase/auth';
import {getServiceDb} from '../../../../../../lib/db';
import {getWorkspaceMemberships, resolveWorkspaceId} from '../../../../../../services/projects';
import {listProjectSources} from '../../../../../../services/downloads';
import {trackExportDownload} from '../../../../../../services/analytics-helpers';

export async function GET(_request: Request, {params}: {params: Promise<{projectId: string}>}) {
  const {projectId} = await params;
  const user = await getSessionUser();
  if (!user) return NextResponse.json({error: 'unauthorized'}, {status: 401});
  const db = getServiceDb();
  const workspaceId = await resolveWorkspaceId(db, user.id);
  if (!workspaceId) return NextResponse.json({error: 'no workspace'}, {status: 403});
  const project = await db.query.projects.findFirst({where: (t, {eq}) => eq(t.id, projectId)});
  if (!project || String(project.workspaceId) !== workspaceId) {
    return NextResponse.json({error: 'not found'}, {status: 404});
  }
  const sources = await listProjectSources(db, projectId);
  const lines = [
    `Sources for "${project.title}"`,
    `Generated by MotionKnowledge — ${new Date().toISOString()}`,
    '',
    ...sources.map((source, index) => {
      const kind = source.kind ?? 'text';
      const url = source.originalUrl ?? '';
      const status = source.status ?? 'unknown';
      return `${index + 1}. [${kind}] ${source.title ?? 'Untitled'}${url ? `\n   URL: ${url}` : ''}\n   Status: ${status}`;
    }),
    '',
    `${sources.length} source(s) recorded.`,
  ];
  trackExportDownload({userId: user.id, workspaceId, projectId, renderId: projectId, kind: 'sources'});
  return new NextResponse(lines.join('\n'), {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Content-Disposition': `attachment; filename="sources.txt"`,
    },
  });
}
